### ISSUE TITLE
It is doesnt work with Freeradius 2.8

### ISSUE THREAD

**Issue by maldalik** [jda/FreeRADIUS-NAS-change-restarter#2]
I tried test it, but get error:
/home/spo/FreeRADIUS-NAS-change-restarter-master# python reloader.py
Reload needed
Traceback (most recent call last):
  File "reloader.py", line 110, in <module>
    if peers_alive(config):
  File "reloader.py", line 74, in peers_alive
    reply = srv.SendPacket(req)
  File "/usr/lib/python2.7/dist-packages/pyrad/client.py", line 159, in SendPacket
    return self._SendPacket(pkt, self.authport)
  File "/usr/lib/python2.7/dist-packages/pyrad/client.py", line 123, in _SendPacket
    self._socket.sendto(pkt.RequestPacket(), (self.server, port))
socket.gaierror: [Errno -2] Name or service not known

**Comment by jda** [comment]
How do you specify your RADIUS servers in your config?
That looks like a error doing a DNS lookup or perhaps a IPv4 vs v6 issue.

**Comment by maldalik** [comment]
Ok. I found my error.  But I don't understand as this script works.
I he thought Freeradius doesn't do service restart
Why to him the user in a radius and what he tries to find there?
If it is possible just to restart service for entry in the table nas_changes?
In your case it turns out that if the client who is registered in .json the file uses the disconnected NAS, then the script ceases to work.
And he is intended for management of NAS loading.

**Comment by jda** [comment]
> If it is possible just to restart service for entry in the table nas_changes?

No. This is specifically for cases where you have more than one RADIUS server and only want to restart one if the there are other servers currently working.

> In your case it turns out that if the client who is registered in .json the file uses the disconnected NAS, then the script ceases to work.

I'm not sure what you mean.

This script is acting as a NAS. You need the secret and IP address configured in FreeRADIUS so it can authenticate to the server as the test user.
